import Head from "next/head";
import { useContext } from "react";
import { MainContext } from "@/state";
import styles from "@/styles/Home.module.scss";
import TodoList from "../components/todoList/TodoList";
import { todos } from "../mock/todos";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next - Todo list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContext.Provider value={todos}>
        <main className={`${styles.Home}`}>
          <TodoList />
        </main>
      </MainContext.Provider>
    </>
  );
}
